valuation_multiple/stock_analysis/urls.py
from django.urls import path
from stock_analysis.views.stocks_view import (
    stock_detail,
    add_stock,
    new_stock,
    create_stock,
)
from stock_analysis.views.fundamental_analysis_view import (
    IndexView,
    detail,
    new_fundamental_analysis,
    create_fundamental_analysis,
    delete_stock_from_fundamental_analysis,
)


app_name = "stock_analysis"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("<int:fundamental_analysis_id>/", detail, name="detail"),
    path("new/", new_fundamental_analysis, name="new"),
    path("create/", create_fundamental_analysis, name="create"),
    path("stock/new/", new_stock, name="new_stock"),
    path("stock/create/", create_stock, name="create_stock"),
    path("stock/<int:stock_id>/", stock_detail, name="stock_detail"),
    path("<int:fundamental_analysis_id>", add_stock, name="add_stock"),
    path(
        "<int:fundamental_analysis_id>/<int:stock_id>",
        delete_stock_from_fundamental_analysis,
        name="delete_stock_from_fundamental_analysis",
    ),
]

valuation_multiple/valuation_multiple/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("stocks/", include("stock_analysis.urls")),
]

valuation_multiple/stock_analysis/models/fundamental_analysis_model.py
from django.db import models
from django.utils import timezone


class FundamentalAnalysis(models.Model):

    # Fundamental Analysis basic information
    name = models.CharField(max_length=30)
    industry = models.CharField(max_length=30)
    last_update = models.DateTimeField(default=timezone.now)

    # Averages of the ratios of the stocks
    avg_price = models.FloatField(default=0)
    avg_current_ratio = models.FloatField(default=0)
    avg_quick_ratio = models.FloatField(default=0)
    avg_cash_ratio = models.FloatField(default=0)
    avg_debt_equity = models.FloatField(default=0)
    avg_inventory_turnover = models.FloatField(default=0)
    avg_days_inventory = models.FloatField(default=0)
    avg_assets_turnover = models.FloatField(default=0)
    avg_return_on_equity = models.FloatField(default=0)
    avg_net_margin = models.FloatField(default=0)
    avg_price_earnings = models.FloatField(default=0)
    avg_price_cash_flow = models.FloatField(default=0)
    avg_price_to_sales = models.FloatField(default=0)
    avg_price_to_book = models.FloatField(default=0)

    # Metadata of the best stock according to model
    best_stock_id = models.IntegerField(default=0)
    best_stock_price_earnings = models.FloatField(default=0)
    best_stock_price_cash_flow = models.FloatField(default=0)
    best_stock_price_to_sales = models.FloatField(default=0)
    best_stock_price_to_book = models.FloatField(default=0)

    # Calculations to determine actual value
    historical = models.FloatField(default=0)
    intrinsic_by_industry = models.FloatField(default=0)
    final_value = models.FloatField(default=0)

    def __str__(self) -> str:
        return self.name

    def __restart_averages(self) -> None:
        self.avg_price = 0
        self.avg_current_ratio = 0
        self.avg_quick_ratio = 0
        self.avg_cash_ratio = 0
        self.avg_debt_equity = 0
        self.avg_inventory_turnover = 0
        self.avg_days_inventory = 0
        self.avg_assets_turnover = 0
        self.avg_return_on_equity = 0
        self.avg_net_margin = 0
        self.avg_price_earnings = 0
        self.avg_price_cash_flow = 0
        self.avg_price_to_sales = 0
        self.avg_price_to_book = 0

    def calculate_avg_ratios(self) -> None:
        stocks = self.stock_set.all()
        if not stocks:
            return

        self.__restart_averages()

        for stock in stocks:
            self.avg_price += stock.price
            self.avg_current_ratio += stock.current_ratio
            self.avg_quick_ratio += stock.quick_ratio
            self.avg_cash_ratio += stock.cash_ratio
            self.avg_debt_equity += stock.debt_equity
            self.avg_inventory_turnover += stock.inventory_turnover
            self.avg_days_inventory += stock.days_inventory
            self.avg_assets_turnover += stock.assets_turnover
            self.avg_return_on_equity += stock.return_on_equity
            self.avg_net_margin += stock.net_margin
            self.avg_price_earnings += stock.price_earnings
            self.avg_price_cash_flow += stock.price_cash_flow
            self.avg_price_to_sales += stock.price_to_sales
            self.avg_price_to_book += stock.price_to_book

        num_stock = len(stocks)

        self.avg_price /= num_stock
        self.avg_current_ratio /= num_stock
        self.avg_quick_ratio /= num_stock
        self.avg_cash_ratio /= num_stock
        self.avg_debt_equity /= num_stock
        self.avg_inventory_turnover /= num_stock
        self.avg_days_inventory /= num_stock
        self.avg_assets_turnover /= num_stock
        self.avg_return_on_equity /= num_stock
        self.avg_net_margin /= num_stock
        self.avg_price_earnings /= num_stock
        self.avg_price_cash_flow /= num_stock
        self.avg_price_to_sales /= num_stock
        self.avg_price_to_book /= num_stock

        self.save()

    def update_best_stock_with_valuation(self, stock, stock_valuation) -> None:
        self.best_stock_id = stock.id
        self.best_percentage = stock_valuation.current_percentage
        self.historical = stock_valuation.historical
        self.intrinsic_by_industry = stock_valuation.intrinsic_by_industry
        self.final_value = stock_valuation.final_value
        self.best_stock_price_earnings = stock_valuation.per_current_value
        self.best_stock_price_cash_flow = stock_valuation.pcf_current_value
        self.best_stock_price_to_sales = stock_valuation.ps_current_value
        self.best_stock_price_to_book = stock_valuation.pbv_current_value

    def calculate_stock_fundamental_analysis(self) -> None:
        stock = self.stock_set.all()[0]
        self.update_best_stock_with_valuation(
            stock=stock, stock_valuation=stock.valuate_stock(self)
        )

        self.save()

    def calculate_best_stock(self) -> None:
        stocks = self.stock_set.all()
        self.best_percentage = float("-inf")

        if not stocks:
            return

        for stock in stocks:
            stock_valuation = stock.valuate_stock(self)

            if stock_valuation.current_percentage > self.best_percentage:
                self.update_best_stock_with_valuation(
                    stock=stock, stock_valuation=stock.valuate_stock(self)
                )

        self.save()

valuation_multiple/stock_analysis/views/fundamental_analysis_view.py
from django.urls import reverse
from django.views import generic
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from stock_analysis.error_handlers.fundamental_analysis_error_handler import (
    get_fundamental_analysis_errors,
)
from stock_analysis.models.stock_model import Stock
from stock_analysis.models.fundamental_analysis_model import FundamentalAnalysis
from stock_analysis.views.stocks_view import get_stocks
from typing import List

class IndexView(generic.ListView):
    template_name = "stock_analysis/index.html"
    context_object_name = "fundamental_analysis_list"

    def get_queryset(self) -> List[FundamentalAnalysis]:
        return FundamentalAnalysis.objects.all()


def detail(request: WSGIRequest, fundamental_analysis_id: int) -> HttpResponse:
    fundamental_analysis = get_object_or_404(
        FundamentalAnalysis, pk=fundamental_analysis_id
    )

    stock = Stock.objects.filter(pk=fundamental_analysis.best_stock_id).first()

    return render(
        request,
        "stock_analysis/detail.html",
        {"fundamental_analysis": fundamental_analysis, "stock": stock},
    )


def new_fundamental_analysis(request: WSGIRequest) -> HttpResponse:
    fundamental_analysis = FundamentalAnalysis()
    return render(
        request,
        "stock_analysis/new.html",
        {
            "fundamental_analysis": fundamental_analysis,
            "tickers": "",
            "first_ticker_analysis": "",
        },
    )


def create_fundamental_analysis(
    request: WSGIRequest,
) -> HttpResponseRedirect:
    fundamental_analysis = FundamentalAnalysis()
    fundamental_analysis.name = request.POST.get("name", "")
    fundamental_analysis.industry = request.POST.get("industry", "")
    first_ticker_analysis = request.POST.get("first_ticker_analysis") == "on"
    tickers = request.POST.get("tickers", "")

    stocks = get_stocks(tickers.upper())
    errors = get_fundamental_analysis_errors(fundamental_analysis, stocks)

    if errors:
        return render(
            request,
            "stock_analysis/new.html",
            {
                "fundamental_analysis": fundamental_analysis,
                "tickers": tickers,
                "errors": errors,
                "first_ticker_analysis": "checked" if first_ticker_analysis else "",
            },
        )

    fundamental_analysis.save()
    for stock in stocks:
        stock.fundamental_analyses.add(fundamental_analysis)
        stock.save()

    fundamental_analysis.calculate_avg_ratios()

    if first_ticker_analysis:
        fundamental_analysis.calculate_stock_fundamental_analysis()
    else:
        fundamental_analysis.calculate_best_stock()

    return HttpResponseRedirect(
        reverse("stock_analysis:detail", args=(fundamental_analysis.id,))
    )


def delete_stock_from_fundamental_analysis(
    request: WSGIRequest, fundamental_analysis_id: int, stock_id: int
) -> HttpResponseRedirect:
    stock = get_object_or_404(Stock, pk=stock_id)
    stock.fundamental_analyses.remove(fundamental_analysis_id)
    fundamental_analysis = get_object_or_404(
        FundamentalAnalysis, pk=fundamental_analysis_id
    )

    fundamental_analysis.calculate_avg_ratios()
    fundamental_analysis.calculate_best_stock()

    return HttpResponseRedirect(
        reverse("stock_analysis:detail", args=(fundamental_analysis_id,))
    )

valuation_multiple/stock_analysis/views/stocks_view.py
from django.urls import reverse
from typing import List
from stock_analysis.models.stock_model import Stock
from stock_analysis.models.fundamental_analysis_model import FundamentalAnalysis
from stock_analysis.error_handlers.stock_error_handler import (
    get_single_stock_errors,
    get_stock_errors,
)
from django.http import HttpResponseRedirect, HttpResponse
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, get_object_or_404


def get_stocks(tickers: str) -> List[Stock]:
    stocks = []

    for ticker in tickers.split():
        stock = Stock.objects.filter(ticker=ticker)

        if stock:
            stocks.append(stock.first())
            continue

        stock = Stock(ticker=ticker)
        if stock.update_stock_ratios():
            stocks.append(stock)
            continue

        stocks.append(ticker)

    return stocks


def stock_detail(request: WSGIRequest, stock_id: int) -> HttpResponse:
    stock = get_object_or_404(Stock, pk=stock_id)
    return render(
        request,
        "stock_analysis/stocks/detail.html",
        {"stock": stock},
    )


def new_stock(request: WSGIRequest) -> HttpResponse:
    stock = Stock()
    return render(
        request, "stock_analysis/stocks/new.html", {"stock": stock, "errors": ""}
    )


def create_stock(request: WSGIRequest) -> HttpResponseRedirect:
    stock = Stock.generate_stock(request)
    errors = get_single_stock_errors(stock)

    if errors:
        return render(
            request,
            "stock_analysis/stocks/new.html",
            {"stock": stock, "errors": errors},
        )

    stock.calculate_real_values()
    stock.save()
    return HttpResponseRedirect(reverse("stock_analysis:stock_detail", args=(stock.id,)))


def add_stock(
    request: WSGIRequest, fundamental_analysis_id: int
) -> HttpResponseRedirect:
    fundamental_analysis = get_object_or_404(
        FundamentalAnalysis, pk=fundamental_analysis_id
    )

    tickers = request.POST.get("tickers", "")
    stocks = get_stocks(tickers.upper())
    errors = get_stock_errors(fundamental_analysis, stocks)

    if errors:
        return render(
            request,
            "stock_analysis/detail.html",
            {
                "fundamental_analysis": fundamental_analysis,
                "tickers": tickers,
                "errors": errors,
            },
        )

    for stock in stocks:
        stock.fundamental_analyses.add(fundamental_analysis)
        stock.save()

    fundamental_analysis.calculate_avg_ratios()
    fundamental_analysis.calculate_best_stock()

    return HttpResponseRedirect(
        reverse("stock_analysis:detail", args=(fundamental_analysis.id,))
    )

valuation_multiple/stock_analysis/templates/stock_analysis/stocks/detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="m-5">
  <div class="d-flex flex-row justify-content-between">
    <h1>{{ stock }}</h1>
    <h1>Stock price: ${{ stock.price }} USD</h1>
  </div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Ratio</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Current Ratio</td>
        <td>{{ stock.current_ratio|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Quick Ratio</td>
        <td>{{ stock.quick_ratio|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Cash Ratio</td>
        <td>{{ stock.cash_ratio|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Debt/Equity</td>
        <td>{{ stock.debt_equity|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Inventory Turnover</td>
        <td>{{ stock.inventory_turnover|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Days Inventory</td>
        <td>{{ stock.days_inventory|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Assets Turnover</td>
        <td>{{ stock.assets_turnover|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Return on Equity</td>
        <td>{{ stock.return_on_equity|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Net Margin</td>
        <td>{{ stock.net_margin|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price Earnings</td>
        <td>{{ stock.price_earnings|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price Cash Flow</td>
        <td>{{ stock.price_cash_flow|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Sales</td>
        <td>{{ stock.price_to_sales|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>5 Years Price to Sales</td>
        <td>{{ stock.price_to_sales_five_years|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Real Price to Sales</td>
        <td>{{ stock.real_price_to_sales|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Book</td>
        <td>{{ stock.price_to_book|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>

  <h3 class="mt-5">Ratios Analysis</h3>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Ratios</th>
        <th scope="col">{{ stock }}</th>
        <th scope="col">5 Years</th>
        <th scope="col">Price</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Price Earnings</td>
        <td>{{ stock.price_earnings|floatformat:2 }}</td>
        <td>{{ stock.price_earnings_five_years|floatformat:2 }}</td>
        <td>{{ stock.price|floatformat:2 }}</td>
        <td>{{ stock.real_price_earnings|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Sales</td>
        <td>{{ stock.price_to_sales|floatformat:2 }}</td>
        <td>{{ stock.price_to_sales_five_years|floatformat:2 }}</td>
        <td>{{ stock.price|floatformat:2 }}</td>
        <td>{{ stock.real_price_to_sales|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Book</td>
        <td>{{ stock.price_to_book|floatformat:2 }}</td>
        <td>{{ stock.price_to_book_five_years|floatformat:2 }}</td>
        <td>{{ stock.price|floatformat:2 }}</td>
        <td>{{ stock.real_price_to_book|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

valuation_multiple/stock_analysis/templates/stock_analysis/stocks/new.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="m-5">
  <h1 class="mt-5 mb-3">New stock</h1>

  {% if errors %}
  <div class="alert alert-danger" role="alert">
    <ul class="mt-3">
      {% for error in errors %}
      <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  <form action="{% url 'stock_analysis:create_stock' %}" method="post">
    {% csrf_token %}
    <div class="d-flex flex-row justify-content-between">
      <div class="form-group">
        <label for="name">Company name</label>
        <input type="text" class="form-control" name="name" id="name", value="{{ stock.name }}">
      </div>
      <div class="form-group">
        <label for="ticker">Ticker</label>
        <input type="text" class="form-control" name="ticker" id="ticker", value="{{ stock.ticker }}">
      </div>
      <div class="form-group">
        <label for="price">Price</label>
        <input type="number" step="any" class="form-control" name="price" id="price", value="{{ stock.price }}">
      </div>
    </div>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Ratio</th>
          <th scope="col">Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Current Ratio</td>
          <td>
            <input type="number" step="any" class="form-control" name="current_ratio" id="current_ratio", value="{{ stock.current_ratio }}">
          </td>
        </tr>
        <tr>
          <td>Quick Ratio</td>
          <td>
            <input type="number" step="any" class="form-control" name="quick_ratio" id="quick_ratio", value="{{ stock.quick_ratio }}">
          </td>
        </tr>
        <tr>
          <td>Cash Ratio</td>
          <td>
            <input type="number" step="any" class="form-control" name="cash_ratio" id="cash_ratio", value="{{ stock.cash_ratio }}">
          </td>
        </tr>
        <tr>
          <td>Debt/Equity</td>
          <td>
            <input type="number" step="any" class="form-control" name="debt_equity" id="debt_equity", value="{{ stock.debt_equity }}">
          </td>
        </tr>
        <tr>
          <td>Inventory Turnover</td>
          <td>
            <input type="number" step="any" class="form-control" name="inventory_turnover" id="inventory_turnover", value="{{ stock.inventory_turnover }}">
          </td>
        </tr>
        <tr>
          <td>Days Inventory</td>
          <td>
            <input type="number" step="any" class="form-control" name="days_inventory" id="days_inventory", value="{{ stock.days_inventory }}">
          </td>
        </tr>
        <tr>
          <td>Assets Turnover</td>
          <td>
            <input type="number" step="any" class="form-control" name="assets_turnover" id="assets_turnover", value="{{ stock.assets_turnover }}">
          </td>
        </tr>
        <tr>
          <td>Return on Equity</td>
          <td>
            <input type="number" step="any" class="form-control" name="return_on_equity" id="return_on_equity", value="{{ stock.return_on_equity }}">
          </td>
        </tr>
        <tr>
          <td>Net Margin</td>
          <td>
            <input type="number" step="any" class="form-control" name="net_margin" id="net_margin", value="{{ stock.net_margin }}">
          </td>
        </tr>
        <tr>
          <td>Price Cash Flow</td>
          <td>
            <input type="number" step="any" class="form-control" name="price_cash_flow" id="price_cash_flow", value="{{ stock.price_cash_flow }}">
          </td>
        </tr>
        <tr>
          <td>Price Earnings</td>
          <td>
            <input type="number" step="any" class="form-control" name="price_earnings" id="price_earnings", value="{{ stock.price_earnings }}">
          </td>
        </tr>
        <tr>
          <td>5 Years Price Earnings</td>
          <td>
            <input type="number" step="any" class="form-control" name="price_earnings_five_years" id="price_earnings_five_years", value="{{ stock.price_earnings_five_years }}">
          </td>
        </tr>
        <tr>
          <td>Price to Sales</td>
          <td>
            <input type="number" step="any" class="form-control" name="price_to_sales" id="price_to_sales", value="{{ stock.price_to_sales }}">
          </td>
        </tr>
        <tr>
          <td>5 Years Price to Sales</td>
          <td>
            <input type="number" step="any" class="form-control" name="price_to_sales_five_years" id="price_to_sales_five_years", value="{{ stock.price_to_sales_five_years }}">
          </td>
        </tr>
        <tr>
          <td>Price to Book</td>
          <td>
            <input type="number" step="any" class="form-control" name="price_to_book" id="price_to_book", value="{{ stock.price_to_book }}">
          </td>
        </tr>
        <tr>
          <td>5 Years Price to Book</td>
          <td>
            <input type="number" step="any" class="form-control" name="price_to_book_five_years" id="price_to_book_five_years", value="{{ stock.price_to_book_five_years }}">
          </td>
        </tr>
      </tbody>
    </table>
    <button type="submit" class="btn btn-success">Add stock</button>
  </form>
</div>
{% endblock %}