valuation_multiple/stock_analysis/urls.py
from django.urls import path
from stock_analysis.views.stocks_view import (
    stock_detail,
    add_stock,
    new_stock,
    create_stock,
)
from stock_analysis.views.fundamental_analysis_view import (
    IndexView,
    detail,
    new_fundamental_analysis,
    create_fundamental_analysis,
    delete_stock_from_fundamental_analysis,
)


app_name = "stock_analysis"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("<int:fundamental_analysis_id>/", detail, name="detail"),
    path("new/", new_fundamental_analysis, name="new"),
    path("create/", create_fundamental_analysis, name="create"),
    path("stock/new/", new_stock, name="new_stock"),
    path("stock/create/", create_stock, name="create_stock"),
    path("stock/<int:stock_id>/", stock_detail, name="stock_detail"),
    path("<int:fundamental_analysis_id>", add_stock, name="add_stock"),
    path(
        "<int:fundamental_analysis_id>/<int:stock_id>",
        delete_stock_from_fundamental_analysis,
        name="delete_stock_from_fundamental_analysis",
    ),
]

valuation_multiple/valuation_multiple/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("stocks/", include("stock_analysis.urls")),
]

valuation_multiple/stock_analysis/models/stock_model.py
import os

from django.db import models
from .fundamental_analysis_model import FundamentalAnalysis
from stock_analysis.classes.stock_valuation import StockValuation
from django.utils import timezone
from django.core.handlers.wsgi import WSGIRequest
from urllib.request import urlopen
import json
import certifi
import yfinance as yf
from statistics import mean
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.environ.get('API_KEY')


class Stock(models.Model):
    fundamental_analyses = models.ManyToManyField(FundamentalAnalysis)

    # Stock basic info
    ticker = models.CharField(max_length=15)
    name = models.CharField(max_length=30)
    last_update = models.DateTimeField(default=timezone.now)

    # Price
    price = models.FloatField(default=0)
    price_bid = models.FloatField(default=0)
    price_ask = models.FloatField(default=0)

    # Ratios
    current_ratio = models.FloatField(default=0)
    quick_ratio = models.FloatField(default=0)
    cash_ratio = models.FloatField(default=0)
    debt_equity = models.FloatField(default=0)
    inventory_turnover = models.FloatField(default=0)
    days_inventory = models.FloatField(default=0)
    assets_turnover = models.FloatField(default=0)
    return_on_equity = models.FloatField(default=0)
    net_margin = models.FloatField(default=0)
    price_earnings = models.FloatField(default=0)
    price_cash_flow = models.FloatField(default=0)
    price_to_sales = models.FloatField(default=0)
    price_to_book = models.FloatField(default=0)

    # Five year ratios
    price_earnings_five_years = models.FloatField(default=0)
    price_to_sales_five_years = models.FloatField(default=0)
    price_to_book_five_years = models.FloatField(default=0)

    # TODO: Verify that this variables are correctly named
    # Real ratios values
    real_price_earnings = models.FloatField(default=0)
    real_price_to_sales = models.FloatField(default=0)
    real_price_to_book = models.FloatField(default=0)

    def __str__(self) -> str:
        return f"{self.ticker}: {self.name}"

    def update_stock_ratios(self) -> bool:
        if not self.__yf_update_stock_ratios():
            return False

        if not self.__financialmodelingprep_update_stock_ratios():
            return False

        self.save()
        return True

    def valuate_stock(self, fundamental_analysis) -> StockValuation:
        historical = (self.real_price_to_sales + self.real_price_to_book) / 2

        per_current_value = (
                self.price * fundamental_analysis.avg_price_earnings / self.price_earnings
        )
        pcf_current_value = (
                self.price * fundamental_analysis.avg_price_cash_flow / self.price_cash_flow
        )
        ps_current_value = (
                self.price * fundamental_analysis.avg_price_to_sales / self.price_to_sales
        )
        pbv_current_value = (
                self.price * fundamental_analysis.avg_price_to_book / self.price_to_book
        )

        intrinsic_by_industry = mean(
            [per_current_value, pcf_current_value, ps_current_value, pbv_current_value]
        )

        final_value = (historical + intrinsic_by_industry) / 2

        stock_valuation = StockValuation(
            final_value=final_value,
            current_percentage=final_value / self.price,
            intrinsic_by_industry=intrinsic_by_industry,
            historical=historical,
            per_current_value=per_current_value,
            pcf_current_value=pcf_current_value,
            ps_current_value=ps_current_value,
            pbv_current_value=pbv_current_value,
        )

        print("======================", stock_valuation)

        return stock_valuation

    def calculate_real_values(self) -> None:
        self.real_price_earnings = (
                self.price * self.price_earnings_five_years / self.price_earnings
        )

        self.real_price_to_sales = (
                self.price * self.price_to_sales_five_years / self.price_to_sales
        )

        self.real_price_to_book = (
                self.price * self.price_to_book_five_years / self.price_to_book
        )

    def __set_five_year_ratios(self, ratios) -> None:
        if len(ratios) >= 5:
            ratios = ratios[:5]

        price_earnings_five_years = []
        price_to_sales_five_years = []
        price_to_book_five_years = []

        for stock in ratios:
            price_earnings_five_years.append(stock["priceEarningsRatio"])
            price_to_sales_five_years.append(stock["priceToSalesRatio"])
            price_to_book_five_years.append(stock["priceToBookRatio"])

        self.price_earnings_five_years = mean(price_earnings_five_years)
        self.price_to_sales_five_years = mean(price_to_sales_five_years)
        self.price_to_book_five_years = mean(price_to_book_five_years)

    def __financialmodelingprep_update_stock_ratios(self) -> bool:
        url = f"https://financialmodelingprep.com/api/v3/ratios/{self.ticker}?apikey={API_KEY}"
        response = urlopen(url, cafile=certifi.where())
        data = response.read().decode("utf-8")
        ratios = json.loads(data)

        if not ratios:
            return False

        latest_year = ratios[0]
        latest_year = {ratio: value or 0 for (ratio, value) in latest_year.items()}

        self.cash_ratio = latest_year["cashRatio"]
        self.inventory_turnover = latest_year["inventoryTurnover"]
        self.assets_turnover = latest_year["assetTurnover"]

        self.net_margin = latest_year["netProfitMargin"]
        self.days_inventory = latest_year["daysOfInventoryOutstanding"]

        self.price_earnings = latest_year["priceEarningsRatio"]
        self.price_cash_flow = latest_year["priceCashFlowRatio"]
        self.price_to_sales = latest_year["priceToSalesRatio"]

        self.__set_five_year_ratios(ratios)
        self.calculate_real_values()

        return True

    def __yf_update_stock_ratios(self) -> bool:
        try:
            ratios = yf.Ticker(self.ticker).info
        except:
            return False

        if not ratios:
            return False

        self.name = ratios["shortName"]
        self.price_ask = ratios["ask"]
        self.price_bid = ratios["bid"]
        self.price = (self.price_bid + self.price_ask) / 2

        self.current_ratio = ratios["currentRatio"]
        self.quick_ratio = ratios["quickRatio"]

        self.debt_equity = ratios["debtToEquity"]
        self.return_on_equity = ratios["returnOnEquity"]
        self.price_to_book = ratios["priceToBook"]

        return True

    def generate_stock(request: WSGIRequest):
        stock = Stock()
        stock.name = request.POST["name"]
        stock.ticker = request.POST["ticker"]
        stock.price = float(request.POST["price"])

        stock.current_ratio = float(request.POST["current_ratio"])
        stock.quick_ratio = float(request.POST["quick_ratio"])
        stock.cash_ratio = float(request.POST["cash_ratio"])
        stock.debt_equity = float(request.POST["debt_equity"])
        stock.inventory_turnover = float(request.POST["inventory_turnover"])
        stock.days_inventory = float(request.POST["days_inventory"])
        stock.assets_turnover = float(request.POST["assets_turnover"])
        stock.return_on_equity = float(request.POST["return_on_equity"])
        stock.net_margin = float(request.POST["net_margin"])
        stock.price_cash_flow = float(request.POST["price_cash_flow"])
        stock.price_earnings = float(request.POST["price_earnings"])
        stock.price_earnings_five_years = float(
            request.POST["price_earnings_five_years"]
        )
        stock.price_to_sales = float(request.POST["price_to_sales"])
        stock.price_to_sales_five_years = float(
            request.POST["price_to_sales_five_years"]
        )
        stock.price_to_book = float(request.POST["price_to_book"])
        stock.price_to_book_five_years = float(request.POST["price_to_book_five_years"])

        return stock

valuation_multiple/stock_analysis/views/fundamental_analysis_view.py
from django.urls import reverse
from django.views import generic
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from stock_analysis.error_handlers.fundamental_analysis_error_handler import (
    get_fundamental_analysis_errors,
)
from stock_analysis.models.stock_model import Stock
from stock_analysis.models.fundamental_analysis_model import FundamentalAnalysis
from stock_analysis.views.stocks_view import get_stocks
from typing import List

class IndexView(generic.ListView):
    template_name = "stock_analysis/index.html"
    context_object_name = "fundamental_analysis_list"

    def get_queryset(self) -> List[FundamentalAnalysis]:
        return FundamentalAnalysis.objects.all()


def detail(request: WSGIRequest, fundamental_analysis_id: int) -> HttpResponse:
    fundamental_analysis = get_object_or_404(
        FundamentalAnalysis, pk=fundamental_analysis_id
    )

    stock = Stock.objects.filter(pk=fundamental_analysis.best_stock_id).first()

    return render(
        request,
        "stock_analysis/detail.html",
        {"fundamental_analysis": fundamental_analysis, "stock": stock},
    )


def new_fundamental_analysis(request: WSGIRequest) -> HttpResponse:
    fundamental_analysis = FundamentalAnalysis()
    return render(
        request,
        "stock_analysis/new.html",
        {
            "fundamental_analysis": fundamental_analysis,
            "tickers": "",
            "first_ticker_analysis": "",
        },
    )


def create_fundamental_analysis(
    request: WSGIRequest,
) -> HttpResponseRedirect:
    fundamental_analysis = FundamentalAnalysis()
    fundamental_analysis.name = request.POST.get("name", "")
    fundamental_analysis.industry = request.POST.get("industry", "")
    first_ticker_analysis = request.POST.get("first_ticker_analysis") == "on"
    tickers = request.POST.get("tickers", "")

    stocks = get_stocks(tickers.upper())
    errors = get_fundamental_analysis_errors(fundamental_analysis, stocks)

    if errors:
        return render(
            request,
            "stock_analysis/new.html",
            {
                "fundamental_analysis": fundamental_analysis,
                "tickers": tickers,
                "errors": errors,
                "first_ticker_analysis": "checked" if first_ticker_analysis else "",
            },
        )

    fundamental_analysis.save()
    for stock in stocks:
        stock.fundamental_analyses.add(fundamental_analysis)
        stock.save()

    fundamental_analysis.calculate_avg_ratios()

    if first_ticker_analysis:
        fundamental_analysis.calculate_stock_fundamental_analysis()
    else:
        fundamental_analysis.calculate_best_stock()

    return HttpResponseRedirect(
        reverse("stock_analysis:detail", args=(fundamental_analysis.id,))
    )


def delete_stock_from_fundamental_analysis(
    request: WSGIRequest, fundamental_analysis_id: int, stock_id: int
) -> HttpResponseRedirect:
    stock = get_object_or_404(Stock, pk=stock_id)
    stock.fundamental_analyses.remove(fundamental_analysis_id)
    fundamental_analysis = get_object_or_404(
        FundamentalAnalysis, pk=fundamental_analysis_id
    )

    fundamental_analysis.calculate_avg_ratios()
    fundamental_analysis.calculate_best_stock()

    return HttpResponseRedirect(
        reverse("stock_analysis:detail", args=(fundamental_analysis_id,))
    )

valuation_multiple/stock_analysis/views/stocks_view.py
from django.urls import reverse
from typing import List
from stock_analysis.models.stock_model import Stock
from stock_analysis.models.fundamental_analysis_model import FundamentalAnalysis
from stock_analysis.error_handlers.stock_error_handler import (
    get_single_stock_errors,
    get_stock_errors,
)
from django.http import HttpResponseRedirect, HttpResponse
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, get_object_or_404


def get_stocks(tickers: str) -> List[Stock]:
    stocks = []

    for ticker in tickers.split():
        stock = Stock.objects.filter(ticker=ticker)

        if stock:
            stocks.append(stock.first())
            continue

        stock = Stock(ticker=ticker)
        if stock.update_stock_ratios():
            stocks.append(stock)
            continue

        stocks.append(ticker)

    return stocks


def stock_detail(request: WSGIRequest, stock_id: int) -> HttpResponse:
    stock = get_object_or_404(Stock, pk=stock_id)
    return render(
        request,
        "stock_analysis/stocks/detail.html",
        {"stock": stock},
    )


def new_stock(request: WSGIRequest) -> HttpResponse:
    stock = Stock()
    return render(
        request, "stock_analysis/stocks/new.html", {"stock": stock, "errors": ""}
    )


def create_stock(request: WSGIRequest) -> HttpResponseRedirect:
    stock = Stock.generate_stock(request)
    errors = get_single_stock_errors(stock)

    if errors:
        return render(
            request,
            "stock_analysis/stocks/new.html",
            {"stock": stock, "errors": errors},
        )

    stock.calculate_real_values()
    stock.save()
    return HttpResponseRedirect(reverse("stock_analysis:stock_detail", args=(stock.id,)))


def add_stock(
    request: WSGIRequest, fundamental_analysis_id: int
) -> HttpResponseRedirect:
    fundamental_analysis = get_object_or_404(
        FundamentalAnalysis, pk=fundamental_analysis_id
    )

    tickers = request.POST.get("tickers", "")
    stocks = get_stocks(tickers.upper())
    errors = get_stock_errors(fundamental_analysis, stocks)

    if errors:
        return render(
            request,
            "stock_analysis/detail.html",
            {
                "fundamental_analysis": fundamental_analysis,
                "tickers": tickers,
                "errors": errors,
            },
        )

    for stock in stocks:
        stock.fundamental_analyses.add(fundamental_analysis)
        stock.save()

    fundamental_analysis.calculate_avg_ratios()
    fundamental_analysis.calculate_best_stock()

    return HttpResponseRedirect(
        reverse("stock_analysis:detail", args=(fundamental_analysis.id,))
    )

valuation_multiple/stock_analysis/templates/stock_analysis/detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="m-5">
  <h1>{{ fundamental_analysis.name }}</h1>
  {% if errors %}
  <div class="alert alert-danger" role="alert">
    <ul class="mt-3">
      {% for error in errors %}
      <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  {% if not fundamental_analysis.stock_set.all %}
  <p>Fundamental analysis has no stocks to analyze</p>
  {% else %}
  <table class="table mb-5">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Ratio</th>
        {% for stock in fundamental_analysis.stock_set.all %}
        <th scope="col">
          <a href="{% url 'stock_analysis:stock_detail' stock.id %}">{{ stock }}</a>
          <a href="{% url 'stock_analysis:delete_stock_from_fundamental_analysis' fundamental_analysis.id stock.id %}">🗑️</a>
        </th>
        {% endfor %}
        <th scope="col">Average</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Price</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>${{ stock.price|floatformat:2 }} USD</td>
        {% endfor %}
        <td>${{ fundamental_analysis.avg_price|floatformat:2 }} USD</td>
        <td></td>
      </tr>
      <tr>
        <td>Current Ratio</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.current_ratio|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_current_ratio|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Quick Ratio</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.quick_ratio|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_quick_ratio|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Cash Ratio</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.cash_ratio|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_cash_ratio|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Debt/Equity</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.debt_equity|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_debt_equity|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Inventory Turnover</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.inventory_turnover|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_inventory_turnover|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Days Inventory</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.days_inventory|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_days_inventory|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Assets Turnover</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.assets_turnover|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_assets_turnover|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Return On Equity</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.return_on_equity|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_return_on_equity|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Net Margin</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.net_margin|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_net_margin|floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <td>Price Earnings</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.price_earnings|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_price_earnings|floatformat:2 }}</td>
        <td>{{ fundamental_analysis.best_stock_price_earnings|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price Cash Flow</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.price_cash_flow|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_price_cash_flow|floatformat:2 }}</td>
        <td>{{ fundamental_analysis.best_stock_price_cash_flow|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Sales</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.price_to_sales|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_price_to_sales|floatformat:2 }}</td>
        <td>{{ fundamental_analysis.best_stock_price_to_sales|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Book</td>
        {% for stock in fundamental_analysis.stock_set.all %}
        <td>{{ stock.price_to_book|floatformat:2 }}</td>
        {% endfor %}
        <td>{{ fundamental_analysis.avg_price_to_book|floatformat:2 }}</td>
        <td>{{ fundamental_analysis.best_stock_price_to_book|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>

  <table class="table mb-5">
    <thead class="thead-dark">
      <tr>
        <th>Ratios</th>
        <th>{{ stock }}</th>
        <th>5 Años</th>
        <th>Precio</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Price Earnings</td>
        <td>{{ stock.price_earnings|floatformat:2 }}</td>
        <td>{{ stock.price_earnings_five_years|floatformat:2 }}</td>
        <td>{{ stock.price|floatformat:2 }}</td>
        <td>{{ stock.real_price_earnings|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Sales</td>
        <td>{{ stock.price_to_sales|floatformat:2 }}</td>
        <td>{{ stock.price_to_sales_five_years|floatformat:2 }}</td>
        <td>{{ stock.price|floatformat:2 }}</td>
        <td>{{ stock.real_price_to_sales|floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Price to Book</td>
        <td>{{ stock.price_to_book|floatformat:2 }}</td>
        <td>{{ stock.price_to_book_five_years|floatformat:2 }}</td>
        <td>{{ stock.price|floatformat:2 }}</td>
        <td>{{ stock.real_price_to_book|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>

  <table class="table mb-5">
    <thead class="thead-dark">
      <tr>
        <th>History</th>
        <th>Intrinsic by Industry</th>
        <th>Final vaue</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ fundamental_analysis.historical|floatformat:2 }}</td>
        <td>{{ fundamental_analysis.intrinsic_by_industry|floatformat:2 }}</td>
        <td>{{ fundamental_analysis.final_value|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>

  {% endif %}

  <form action="{% url 'stock_analysis:add_stock' fundamental_analysis.id %}" method="post">
    {% csrf_token %}
    <fieldset>
      <div class="form-group">
        <label for="name">Add tickers (write ticker names separated by spaces)</label>
        <input type="text" class="form-control" name="tickers" id="tickers" value="{{ tickers }}">
      </div>
      <button type="submit" class="btn btn-success">Add ticker</button>
    </fieldset>
  </form>
</div>
{% endblock %}

valuation_multiple/stock_analysis/templates/stock_analysis/index.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="m-5">
  <header class="d-flex justify-content-between">
    <h1>My fundamental analysis</h1>
    <a href="{% url 'stock_analysis:new' %}">
      <button type="button" class="btn btn-primary ml-5 mt-1">New fundamental analysis</button>
    </a>
  </header>
  <main>
    {% if fundamental_analysis_list %}
      <ul>
      {% for fundamental_analysis in fundamental_analysis_list %}
        <li>
          <a href="{% url 'stock_analysis:detail' fundamental_analysis.id %}">
            {{ fundamental_analysis.name }}
          </a>
        </li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No fundamental analysis available</p>
    {% endif %}
  </main>
</div>
{% endblock %}

valuation_multiple/stock_analysis/templates/stock_analysis/new.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="m-5">
        <header class="mb-2">
            <h1>New fundamental analysis</h1>
        </header>
        <main>

            {% if errors %}
                <div class="alert alert-danger" role="alert">
                    <ul class="mt-3">
                        {% for error in errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <form action="{% url 'stock_analysis:create' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" name="name" id="name"
                               value="{{ fundamental_analysis.name }}">
                    </div>
                    <div class="form-group">
                        <label for="name">Industry</label>
                        <input type="text" class="form-control" name="industry" id="industry"
                               value="{{ fundamental_analysis.industry }}">
                    </div>
                    <div class="form-group">
                        <label for="name">Tickers (write ticker names separated by spaces)</label>
                        <input type="text" class="form-control" name="tickers" id="tickers" value="{{ tickers }}">
                    </div>
                    <div class="form-check mb-5">
                        <input type="checkbox" class="form-check-input" name="first_ticker_analysis"
                               id="first_ticker_analysis" {% if first_ticker_analysis %}checked{% endif %}>
                        <label class="form-check-label" for="first_ticker_analysis">
                            Do fundamental analysis based on the first ticker of the analysis
                        </label>
                    </div>

                    <button type="submit" class="btn btn-success">Create</button>
                </fieldset>
            </form>
        </main>
    </div>
{% endblock %}